# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="robbyrussell"
ZSH_THEME="honukai"

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# plugins=(git bower common-aliases docker encode64 git-extras gradle mvn npm pip pod python redis-cli sbt wd zsh-autosuggestions zsh-syntax-highlighting )
plugins=(git docker encode64 git-extras wd zsh-autosuggestions zsh-syntax-highlighting zsh-history-substring-search)
      
# Java Encoding
alias javac='javac -J-Dfile.encoding=UTF-8 -encoding UTF-8 '
alias java='java -Dfile.encoding=UTF-8'


cdl() { cd "$@" && pwd ; ls -al; }
alias ..="cdl .."
alias ...="cd ../.."
alias psg='ps aux | grep -v grep | grep -i --color'
alias c='clear'
alias hosts='vim /etc/hosts'
alias mci='mvn clean install'
alias mct='mvn clean test'

# ubuntu 旋转显示器
# 向左旋转90度
alias tleft='xrandr -o left'
# 向右旋转90度
alias tright='xrandr -o right'
# 上下翻转
alias tleft='xrandr -o inverted'
# 回到正常角度
alias tleft='xrandr -o normal'

function startproxy {
   export http_proxy="http://127.0.0.1:8123"
   export https_proxy="http://127.0.0.1:8123"
}


source $ZSH/oh-my-zsh.sh
## plugins bind
# zsh-history-substring-search
#bindkey -M vicmd 'k' history-substring-search-up
#bindkey -M vicmd 'j' history-substring-search-down


# 调整屏幕亮度
alias blight='~/xianyue/workspace/own/dotfiles/shell/blight.sh'
 
# golang
# go安装路径
export GOROOT=/usr/local/go
# 默认安装包路径
export GOPATH=$HOME/xianyue/workspace/go/gowork

# 切换源
export GO111MODULE=on
export GOPROXY=https://goproxy.cn
 
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$GOPATH/bin
 
export JAVA_HOME=/usr/local/java/jdk1.8.0_202
 
export JRE_HOME=/usr/local/java/jdk1.8.0_202/jre
export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JRE_HOME/lib
 
export PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin

# You may need to manually set your language environment
# export LANG=en_US.UTF-8


# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# source /etc/profile
#source ~/.profile
# source ~/.vimrc
unsetopt AUTO_CD

wd() {
    . /usr/share/wd/wd.sh
}

